CMAPS = {'Nestlet_Score': 'blue',
         'Marbles': 'blue',
         'OF_stereo_count_first': 'blue',
         'OF_stereo_count_after': 'blue',
         'OF_distance_first': 'green',
         'OF_distance_after': 'green',
         'OF_habituation': 'green',
         'OF_movement_first': 'green',
         'OF_movement_after': 'green',
         'Rotarod_latency_1': 'green',
         'Rotarod_latency_2': 'green',
         'Rotarod_latency_3': 'green',
         'Rotarod_shortterm': 'green',
         'Rotarod_longterm': 'green',
         'OF_center_first': 'yellow',
         'OF_center_after': 'yellow',
         'OF_horizontal_first': 'gray',
         'OF_horizontal_after': 'gray',
         'OF_vertical_first': 'gray',
         'OF_vertical_after': 'gray',
         'EPM_OT': 'orange',
         'EPM_OT_TT': 'orange',
         'EPM_OE_TE': 'orange',
         'EMP_anxiety': 'orange',
         'Splash': 'brown',
         'Social_interaction': 'purple',
         'TCT_sociability_1': 'purple',
         'TCT_novelty_1': 'purple',
         'TCT_sociability_2': 'purple',
         'TCT_novelty_2': 'purple'}

DROP_COLUMNS = ['OF_stereo_count_first',
                'OF_distance_first',
                'OF_movement_first',
                'OF_center_first',
                'OF_horizontal_first',
                'OF_vertical_first',
                'TCT_sociability_2',
                'TCT_novelty_2',
                'EPM_OE_TE',
                'EMP_anxiety']

